### PR TITLE
Update linter.yml

### PR DESCRIPTION
**Pull request by I-Cat**

### CODE REVIEW

**Comment by I-Cat** [comment]
pass

**Comment by PrestonN** [comment]
Can I ask what the purpose of this PR is?  The linter CI seems to work just fine and doesn't need a line to install eslint.  That and the extra comments seem unneeded as well.  If there is a good reason then please let me know.  If not, then I will be closing this soon.

**Comment by I-Cat** [comment]
My mistake

**Comment by I-Cat** [comment]
My mistake

**Pull request closed without merging**
